(define (make-draw player)
  (let* ((window (make-window width height "Tower Defense" 60))
         (background-layer ((window 'new-layer!)))
         (entity-layer ((window 'new-layer!)))
         (projectile-layer ((window 'new-layer!)))
         (text-layer ((window 'new-layer!)))
         (text (make-tile width height))
         (start-text (make-tile width height))
         (previous-text '()))
    
    (define (reposition! tile position)
      ((tile 'set-x!) (+ (- (/ (* (tile 'get-w) size-factor) 2) (/ (tile 'get-w) 2)) (position 'get-x)))
      ((tile 'set-y!) (+ (- (/ (* (tile 'get-h) size-factor) 2) (/ (tile 'get-h) 2)) (position 'get-y))))

    (define (draw! drawable)
      ((entity-layer 'add-drawable!) drawable))

    (define (draw-start-text)
      ((start-text 'draw-text!) "Press: s to start..." (* size-factor 25) (* size-factor 300) (* size-factor 200) "white")
      ((text-layer 'add-drawable!) start-text))

    (define (draw-game-status-text)
      (if (not (null? previous-text))
          ((text-layer 'remove-drawable!) previous-text))
      (let ((text-tile (make-tile width height)))
        ((text-tile 'draw-text!) (string-append "Points: " (number->string (player 'get-points))) (* size-factor 10) (* size-factor 700) (* size-factor 100) "black")
        ((text-layer 'add-drawable!) text-tile)
        (set! previous-text text-tile)))

    (define (remove-start-text!)
      ((text-layer 'remove-drawable!) start-text))

    (define (remove-previous-text!)
      (if (not (null? previous-text))
          (begin ((text-layer 'remove-drawable!) previous-text)
                 (set! previous-text'()))))
    
    (define (draw-world!)
      (let ((tile (make-tile width height))
            (restart-text (make-tile width height)))
        ((tile 'draw-rectangle!) 0 0 width height "green")
        ((tile 'draw-rectangle!) (start-position 'get-x) (start-position 'get-y) (* 300 size-factor) (* 50 size-factor) "brown") ;Pad ((0,5) -> (15,5)) (division)
        ((tile 'draw-rectangle!) (* 300 size-factor) (* 100 size-factor) (* size-factor 50) (* 400 size-factor) "brown") ;Pad ((15,5) -> (15,35)) (division)
        ((tile 'draw-rectangle!) (* size-factor 300) (* size-factor 500) (* 500 size-factor)  (* 50 size-factor) "brown") ;Pad ((15,35) -> (40,35)) (division)
        ((background-layer 'add-drawable!) tile)
        ((restart-text 'draw-text!) "Press 'space' to restart" (* size-factor 12) (* size-factor 600) (* size-factor 50) "black")
        ((text-layer 'add-drawable!) restart-text)))


    (define (dispatch mes)
      (cond ((eq? mes 'draw!) draw!)
            ((eq? mes 'reposition!) reposition!)
            ((eq? mes 'draw-world!) (draw-world!))
            ((eq? mes 'get-window) window)
            ((eq? mes 'entity-layer) entity-layer)
            ((eq? mes 'tower-layer) tower-layer)
            ((eq? mes 'projectile-layer) projectile-layer)
            ((eq? mes 'get-background-layer) background-layer)
            ((eq? mes 'draw-start-text) draw-start-text)
            ((eq? mes 'get-start-text) start-text)
            ((eq? mes 'get-text-layer) text-layer)
            ((eq? mes 'draw-game-status-text) draw-game-status-text)
            ((eq? mes 'remove-start-text!) remove-start-text!)
            ((eq? mes 'empty-used-tiles!) empty-used-tiles!)
            ((eq? mes 'remove-all-text!) remove-all-text!)
            ((eq? mes 'remove-previous-text!) remove-previous-text!)
            (else (display "Error: Wrong dispatch message (Draw.rkt) ") (display mes))))
    dispatch))