(define (make-wave environment)
  (let ((wave 0)
        (wave-amount 4)
        (wave-list '())
        (wave-ready? #f)
        (game-over? #f))
  
    (define (next-monster!)
      (if (not (null? wave-list))
          (begin ((environment 'add-entity!) (car wave-list))
                 (set! wave-list (cdr wave-list)))))

    (define (fill-wave-list monster-list) ;List with monster and amount
      (define (iter lijst)
        (if (not (null? lijst))
            (let ((monster-cons (car lijst)))
              (do ((i 0 (+ i 1)))
                ((= i (cdr monster-cons)))      ; maybe return the last value of the iteration
                (set! wave-list (add-element-to-list (make-monster (car monster-cons) (make-position (start-position 'get-x) (start-position 'get-y))) wave-list))))
            (iter (cdr lijst))))
      (iter monster-list))

    (define (wave-process)
      (if (and (null? wave-list) (null? (environment 'get-monsters)) (not wave-ready?))
          (if (> (+ wave 1) wave-amount)
              (set! game-over? #t)
              (begin
                (set! wave-ready? #t)
                (((environment 'draw) 'draw-wave-text!))
                ((environment 'remove-all-projectiles!))))))

    (define (start-wave!)
      (set-wave! 0)
      (set-wave-list! '())
      (load-wave!))

    (define (set-wave! val)
      (set! wave val))

    (define (set-wave-list! val)
      (set! wave-list val))
  
    (define (load-wave!)
      (set! wave (+ wave 1))
      (((environment 'draw) 'update-wave-count!) wave)
      (cond ((= wave 1) (fill-wave-list (list (cons "Red" 3))))
            ((= wave 2) (fill-wave-list (list (cons "Blue" 1))))
            ((= wave 3) (begin
                          (fill-wave-list (list (cons "Gray" 1)))
                          (fill-wave-list (list (cons "Red" 3)))
                          (fill-wave-list (list (cons "Blue" 2)))))
            ((= wave 4) (begin
                          (fill-wave-list (list (cons "Purple" 1)))
                          (fill-wave-list (list (cons "Red" 8))))))
      (set! wave-ready? #f))

    (define (set-wave-ready! val)
      (set! wave-ready? val))

    (define (reset!)
      (set! wave 0)
      (set! wave-list '())
      (set! wave-ready? #f))
  
    (define (dispatch mes)
      (cond ((eq? mes 'next-monster!) next-monster!)
            ((eq? mes 'load-wave!) load-wave!)
            ((eq? mes 'get-wave) wave)
            ((eq? mes 'set-wave!) set-wave!)
            ((eq? mes 'get-wave-list) wave-list)
            ((eq? mes 'set-wave-list!) set-wave-list!)
            ((eq? mes 'start-wave!) start-wave!)
            ((eq? mes 'wave-ready?) wave-ready?)
            ((eq? mes 'set-wave-ready!) set-wave-ready!)
            ((eq? mes 'reset!) reset!)
            ((eq? mes 'wave-process) wave-process)
            ((eq? mes 'wave-amount) wave-amount)
            ((eq? mes 'game-over?) game-over?)
            (else (display "Error: Wrong dispatch message (Wave.rkt) -> ") (display mes))))
    dispatch))